### ISSUE TITLE
VPATH build may fail

### ISSUE THREAD

**Issue by wkliao** [DataLib-ECP/vol-log-based#14]
I suspect this line may fail when doing VPATH build.
https://github.com/DataLib-ECP/vol-log-based/blob/e4c61c252b5799745c78c61e58ff08e57bd7e837/configure.ac#L573

**Comment by khou2020** [comment]
fixed

**Comment by wkliao** [comment]
VPATH build failed on "make check" and "make ptest" for qmcpack and openPMD.

QMCPACK
```
./restart -g "1 1 1"
...
In direct memory block for handle type COMM, 1 handles are still allocated
```
OpenPMD
```
mpiexec -n 4 ./8a_benchmark_write_parallel > 8a_benchmark_write_parallel.log
./8a_benchmark_write_parallel: error while loading shared libraries: libopenPMD.so: cannot open shared object file: No such file or directory
```

**Comment by khou2020** [comment]
> VPATH build failed on "make check" and "make ptest" for qmcpack and openPMD.
> 
> QMCPACK
> 
> ```
> ./restart -g "1 1 1"
> ...
> In direct memory block for handle type COMM, 1 handles are still allocated
> ```
> 
> OpenPMD
> 
> ```
> mpiexec -n 4 ./8a_benchmark_write_parallel > 8a_benchmark_write_parallel.log
> ./8a_benchmark_write_parallel: error while loading shared libraries: libopenPMD.so: cannot open shared object file: No such file or directory
> ```

fixed

**Comment by wkliao** [comment]
Got an error when running
```
make -s distcheck DISTCHECK_CONFIGURE_FLAGS="--silent --enable-zlib --with-hdf5=${SCRATCH}/HDF5/1.13.0 --enable-test-netcdf4=$SCRATCH/NetCDF/4.8.1 --enable-test-openpmd --enable-test-qmcpack"

...

make[1]: *** [Makefile:739: distcleancheck] Error 1
make: *** [Makefile:670: distcheck] Error 1
```

**Comment by wkliao** [comment]
We also need to run a test program to verify the output HDF5 files of individual tests are in yhe log-based layout.

**Comment by wkliao** [comment]
See PR #15
