### ISSUE TITLE
Compilation fails.

### ISSUE THREAD

**Issue by hyoklee** [DataLib-ECP/vol-log-based#2]
The previous commit [1] compiled fine but the latest doesn't:

```H5VL_logi.hpp:10:10: fatal error: H5VL_logi_profiling.hpp: No such file or directory
     336     #include "H5VL_logi_profiling.hpp"
     337              ^~~~~~~~~~~~~~~~~~~~~~~~~
     338    compilation terminated.
```

I tested it on Linux  3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux.

[1] https://github.com/DataLib-ECP/vol-log-based/commit/b13778efd9e0c79135a9d7352104985408078d45

**Comment by khou2020** [comment]
It should be fixed.

**Comment by hyoklee** [comment]
@khou2020 , I have a new problem:

```
  >> 356    H5VL_logi_profiling.cpp:23:20: error: 'H5VL_LOG_NTIMER' was not declared in this scope
     357     static double tmax[H5VL_LOG_NTIMER], tmin[H5VL_LOG_NTIMER], tmean[H5VL_LOG_NTIMER], tvar[H5VL_LOG_NTIMER], tvar_local[H5VL_LOG_NTIMER];
     358                        ^~~~~~~~~~~~~~~
```
Would you please add a GitHub Action so I can verify the fix more easily?

Here's a sample Action that I use in my fork:

https://github.com/hyoklee/vol-log-based/blob/master/.github/workflows/linux.yml

**Comment by brtnfld** [comment]
> It should be fixed.

@khou2020 The file H5VL_logi_profiling.hpp is missing.

**Comment by wkliao** [comment]
> Here's a sample Action that I use in my fork:
> 
> https://github.com/hyoklee/vol-log-based/blob/master/.github/workflows/linux.yml

That is a good suggestion. Thanks! @hyoklee 
@khou2020 Let's do that.
It should also be able to detect the error @brtnfld encountered.
