### ISSUE TITLE
strncpy

### ISSUE THREAD

**Issue by wkliao** [DataLib-ECP/vol-log-based#37]
https://github.com/DataLib-ECP/vol-log-based/blob/8b68e0f460edb3b2955c6dfcc7ef5c36d02a9301/src/H5VL_logi_util.hpp#L103-L115

This code block is problematic.
1. strncpy cannot copy more than strlen(name) from `name`.
2. How is `ret` freed latter if name[0] == '_' ?

**Comment by yzanhua** [comment]
> strncpy cannot copy more than strlen(name) from name

According to [cppreference](https://en.cppreference.com/w/c/string/byte/strncpy), strncpy will take care of the overflow problem and will always automatically append `\0` if it tries to copy more than strlen(name) from `name`. So the original code should work fine.

**Comment by wkliao** [comment]
Have you seen the compile warning message from the github action log?

**Comment by wkliao** [comment]
Consider using memcpy instead of strncpy.
