### ISSUE TITLE
Unable to find H5VL_logi_profiling.m4 files

### ISSUE THREAD

**Issue by brtnfld** [DataLib-ECP/vol-log-based#5]
The Autotools configure assume in-source builds, for out-of-source builds, it can not find the m4 files.

Making all in src
make[2]: Entering directory '/autofs/nccs-svm1_home1/brtnfld/packages/vol-log-based/build/src'
m4  -I../../m4 ../../src/H5VL_logi_profiling.m4h >H5VL_logi_profiling.hpp
m4:../../src/H5VL_logi_profiling.m4h:16: cannot open `H5VL_logi_profiling_timers.m4': No such file or directory

**Comment by khou2020** [comment]
added support for out-of-source builds
