### ISSUE TITLE
configure mentions non-existant make command.

### ISSUE THREAD

**Issue by brtnfld** [DataLib-ECP/vol-log-based#9]
As far as I can tell there is no "ptest" for make:

./configure.ac:AC_ARG_VAR(TESTMPIRUN, [MPI run command for "make ptest", @<:@default: mpiexec -n NP@:>@])
./configure.ac:AC_ARG_VAR(TESTOUTDIR, [Output file directory for "make check" and "make ptest", @<:@default: ./@:>@])

**Comment by khou2020** [comment]
It is left for future extension and should not cause any problem in the build.

**Comment by wkliao** [comment]
@khou2020 
Please comment out those 2 lines.
Once parallel test feature is added in the future, we will uncomment them.
Otherwise the configure help messages are misleading.

**Comment by brtnfld** [comment]
I'm confused, aren't the tests in test/basic parallel (run with "make check")? Are they only meant to be run with one rank?

**Comment by wkliao** [comment]
Currently "make check" only run test program sequentially.
See file test/basic/wrap_runs.sh
We will add make target "ptest" soon.

**Comment by brtnfld** [comment]
hmm, I guess that is why it is segfaulting on summit. I could not get make check to pass there, so I had to run the tests manually.

I was just testing the install because my QMCPACK benchmark is segfaulting on summit with the VOL.

**Comment by khou2020** [comment]
It is commented out. Can you share your application that crashed logvol?

**Comment by khou2020** [comment]
> hmm, I guess that is why it is segfaulting on summit. I could not get make check to pass there, so I had to run the tests manually.
> 
> I was just testing the install because my QMCPACK benchmark is segfaulting on summit with the VOL.

Can you share the QMCPACK  benchmark? Also the way you build and ran it.

**Comment by khou2020** [comment]
Moved to issue 10.
